"""
WHY:
The StudentResponse schema defines the structure of student objects returned by
the API. It ensures that all outgoing data is consistent with the SQLAlchemy
Student model and provides a clean, predictable format for clients consuming the
API. Using from_attributes=True allows Pydantic v2 to serialize SQLAlchemy ORM
objects directly without manual conversion, keeping response handling simple and
fully aligned with typed ORM models.

DESIGN:
1. The id field is required and reflects the primary key generated by the
   database, ensuring that every returned student can be uniquely identified.

2. The username and email fields mirror the database constraints, guaranteeing
   that response data remains consistent with the StudentCreate and StudentUpdate
   schemas as well as the SQLAlchemy model.

3. The major field is optional and capped at 50 characters, matching the
   database column definition and ensuring consistent formatting across all
   returned student records.

4. The gpa field is optional but validated to fall within the 0.0–4.0 academic
   range, ensuring that only realistic values are returned to clients.

5. The model_config uses from_attributes=True, enabling Pydantic to read fields
   directly from SQLAlchemy model instances. This eliminates the need for manual
   dict conversion and ensures seamless ORM integration across all CRUD
   endpoints.

Together, these design choices create a reliable, typed, and fully aligned
response schema that guarantees consistent, predictable output for all student
operations.
"""



from pydantic import BaseModel, ConfigDict, Field
from typing import Optional
from datetime import datetime

class StudentResponse(BaseModel):
    id: int
    username: str = Field(max_length=75)
    email: str = Field(max_length=100)
    major: Optional[str] = Field(default=None, max_length=50)
    gpa: Optional[float] = Field(default=None, ge=0.0, le=4.0)

    model_config = ConfigDict(from_attributes=True)
