"""
WHY:
The StudentResponse schema defines the structure of student objects returned by
the API. It ensures that all outgoing data is consistent with the SQLAlchemy
Student model and provides a clean, predictable format for clients consuming the
API. Using from_attributes=True allows Pydantic to serialize SQLAlchemy ORM
objects directly without manual conversion.

DESIGN:
1. The id field is required and reflects the primary key generated by the
   database, ensuring that every returned student can be uniquely identified.

2. The name and email fields mirror the database constraints, guaranteeing that
   response data remains consistent with the StudentCreate and StudentUpdate
   schemas.

3. The major field is optional and capped at 50 characters, matching the
   database column definition and preventing overly long academic labels.

4. The gpa field is optional but validated to fall within the 0.0–4.0 range,
   ensuring that only realistic academic values are returned.

5. The model_config uses from_attributes=True, enabling Pydantic to read fields
   directly from SQLAlchemy model instances. This eliminates the need for manual
   dict conversion and ensures seamless ORM integration.

Overall, this schema provides a clean, validated, and database‑aligned structure
for all student responses, ensuring consistency and reliability across the API.
"""


from pydantic import BaseModel, ConfigDict, Field
from typing import Optional
from datetime import datetime

class StudentResponse(BaseModel):
    id: int
    name: str = Field(max_length=75)
    email: str = Field(max_length=100)
    major: Optional[str] = Field(default=None, max_length=50)
    gpa: Optional[float] = Field(default=None, ge=0.0, le=4.0)

    model_config = ConfigDict(from_attributes=True)
